name: TELECHARGEMENT-BDD
on:
  schedule:
    - cron:  '0 5 * * 1'
  workflow_dispatch:

jobs:
  TELECHARGEMENTS-BDD:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Téléchargement des bases de données
        run:  |
          ./SCRIPTS/BDD.ps1
      
      - name: Sauvegarde des cartes de l'ONEM
        run:  |
          ./SCRIPTS/sauvegarde_onem.ps1